#ifndef CONFIG_H
#define CONFIG_H


    #include <def.h>

    #define DEBUG_CONFIG 1
    #define PEACHOS_MAX_PATH 108
    #define PEACHOS_IDT_MAX_SIZE 256
    #define IDT_TABLE_SIZE PEACHOS_IDT_MAX_SIZE
    #define PEACHOS_SECTOR_SIZE 512
    #define PEACHOS_HEAP_BLOCK_COUNT 4096
    #define PEACHOS_HEAP_SIZE (64 MB) 
    #define PEACHOS_HTABLE_START_ADDRESS ((void*)0x01000000)
    #define PEACHOS_HEAP_START_ADDRESS   ((void*)(0x01000000 + (PEACHOS_HEAP_SIZE/PEACHOS_HEAP_BLOCK_COUNT) ))
    #define PEACHOS_MAX_FILESYSTEMS  10
    #define PEACHOS_MAX_FILE_DESCRIPTORS 1024


#endif 